assertNoLeakedSecrets: false   # les secret sont chiffrés par helm

persistence:
  enabled: false
  type: pvc
  storageClassName: azurefile-csi
  size: 10Gi

replicas: 1

initChownData: 
  enabled: false

datasources:
    datasources.yaml:
        apiVersion: 1
        datasources:
            - name: prometheus
              type: prometheus
              url: http://prometheus-server:9090
              isDefault: true
              timeInterval: 2m
grafana.ini:
  server:
    root_url: "https://%(domain)s/"
    domain: grafana.alimeul2024.ovh
  users:
    allow_sign_up: false
    auto_assign_org: true
    auto_assign_org_role: Editor
    skip_org_role_sync: true

deploymentStrategy:
  type: Recreate

resources:
  requests: 
    cpu: 100m
    memory: 192Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  port: 3000

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "grafana-dashboards-kubernetes"
        orgId: 1
        folder: "Kubernetes"
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes


dashboards:
  k8s:
    k8s-views-global:
      gnetId: 15757
      revision: 43
      datasource: prometheus
    k8s-views-namespaces:
      gnetId: 15758
      revision: 42
      datasource: prometheus
    k8s-views-nodes:
      gnetId: 15759
      revision: 37
      datasource: prometheus
    k8s-views-pods:
      gnetId: 15760
      revision: 36
      datasource: prometheus
    k8s-system-api-server:
      gnetId: 15761
      revision: 19
      datasource: prometheus
    k8s-system-coredns:
      gnetId: 15762
      revision: 20